[package]
name = "deq"
version = "0.1.0"
authors = ["ebiiim <mail@ebiiim.com>"]
edition = "2018"

[dependencies]
portaudio = "0.7"
log = { version = "0.4", features = ["release_max_level_warn"] }
env_logger = "0.9"
