[package]
name = "deq_filter"
version = "0.1.0-dev"
authors = ["Shunsuke Ise <ise@ebiiim.com>"]
edition = "2018"
repository = "https://github.com/ebiiim/deq"

[dependencies]
log = { version = "0.4", features = ["release_max_level_warn"] }
